export let productList = [
  {
    name: "Банан",
    price: 100,
    measurement: "Кг",
    category: "Овощи и Фрукты",
    imgsrc: "../public/images/CardItems/banana.jpg",
    discount: 0,
    counter: 1,
  },
  {
    name: "Ананас",
    price: 200,
    measurement: "Кг",
    category: "Овощи и Фрукты",
    imgsrc: "../public/images/CardItems/ananas.jpg",
    discount: 4,
    counter: 1,
  },
  {
    name: "Яблоко",
    price: 80,
    measurement: "Кг",
    category: "Овощи и Фрукты",
    imgsrc: "../public/images/CardItems/apple.jpg",
    discount: 0,
    counter: 1,
  },
  {
    name: "Киви",
    price: 100,
    measurement: "Кг",
    category: "Овощи и Фрукты",
    imgsrc: "../public/images/CardItems/qiwi.jpg",
    discount: 6,
    counter: 1,
  },
  {
    name: "Молоко",
    price: 110,
    measurement: "Литр",
    category: "Молочная продукция",
    imgsrc: "../public/images/CardItems/milk.jpg",
    discount: 0,
    counter: 1,
  },
  {
    name: "Сметана",
    price: 90,
    measurement: "Пачку",
    category: "Молочная продукция",
    imgsrc: "../public/images/CardItems/smetana.jpg",
    discount: 0,
    counter: 1,
  },
  {
    name: "Масло Растительное",
    measurement: "Шт",
    price: 150,
    category: "Молочная продукция",
    imgsrc: "../public/images/CardItems/oil.jpg",
    discount: 2,
    counter: 1,
  },
  {
    name: "Курица",
    price: 250,
    measurement: "Кг",
    category: "Мясо",
    imgsrc: "../public/images/CardItems/chiken.jpg",
    discount: 15,
    counter: 1,
  },
  {
    name: "Говядина",
    price: 400,
    measurement: "Кг",
    category: "Мясо",
    imgsrc: "../public/images/CardItems/beef.jpg",
    discount: 0,
    counter: 1,
  },
  {
    name: "Пельмени замороженные",
    price: 300,
    measurement: "1 Пачку",
    category: "Замороженные продукты",
    imgsrc: "../public/images/CardItems/pelmeni.jpg",
    discount: 0,
    counter: 1,
  },
  {
    name: "Хлеб",
    price: 50,
    measurement: "Шт",
    category: "Бакалея",
    imgsrc: "../public/images/CardItems/bread.jpg",
    discount: 0,
    counter: 1,
  },
  {
    name: "Мука для выпечки",
    price: 70,
    measurement: "Кг",
    category: "Бакалея",
    imgsrc: "../public/images/CardItems/muka.jpg",
    discount: 0,
    counter: 1,
  },
  {
    name: "Яйца куриные 0С",
    measurement: "10 Шт",
    price: 100,
    category: "Продукты питания",
    imgsrc: "../public/images/CardItems/eggs.jpg",
    discount: 5,
    counter: 1,
  },
  {
    name: "Сок Апельсиновый",
    measurement: "Литр",
    price: 150,
    category: "Напитки и десерты",
    imgsrc: "../public/images/CardItems/juice.jpg",
    discount: 0,
    counter: 1,
  },
  {
    name: "Мороженое",
    measurement: "Шт",
    price: 100,
    category: "Напитки и десерты",
    imgsrc: "../public/images/CardItems/ice-creame.jpg",
    discount: 10,
    counter: 1,
  },
  {
    name: "Соль Поваренная, пищевая",
    measurement: "Шт",
    price: 40,
    category: "Бакалея",
    imgsrc: "../public/images/CardItems/salt.jpg",
    discount: 0,
    counter: 1,
  },
  {
    name: "Торт Сказка",
    measurement: "Шт",
    price: 400,
    category: "Напитки и десерты",
    imgsrc: "../public/images/CardItems/tort.jpg",
    discount: 20,
    counter: 1,
  },
  {
    name: "Сахарный песок",
    measurement: "Кг",
    price: 76,
    category: "Бакалея",
    imgsrc: "../public/images/CardItems/sugar.jpg",
    discount: 0,
    counter: 1,
  },
  {
    name: "Шоколад Ritter Sport",
    measurement: "Шт",
    price: 119,
    category: "Напитки и десерты",
    imgsrc: "../public/images/CardItems/chocolate.png",
    discount: 10,
    counter: 1,
  },
];
